# Generated by Django 5.0.3 on 2024-03-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_options_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='dest',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='dest',
            new_name='floor',
        ),
    ]
