# Generated by Django 5.0.3 on 2024-03-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_room_name_book_bus_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_name',
            new_name='room_name',
        ),
    ]
