# Generated by Django 5.0.3 on 2024-03-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_busid_book_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_name',
            new_name='room_name',
        ),
    ]
