# Generated by Django 5.0.3 on 2024-03-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_bus_name_book_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'List of Rooms'},
        ),
    ]
