# Generated by Django 5.0.3 on 2024-03-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_bus_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='Room',
        ),
    ]
