# Generated by Django 5.0.2 on 2024-03-25 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_bus_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 3, 25, 8, 42, 39, 336291, tzinfo=datetime.timezone.utc), upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 3, 25, 8, 42, 50, 231964, tzinfo=datetime.timezone.utc), upload_to='img/'),
            preserve_default=False,
        ),
    ]
