# Generated by Django 5.0.2 on 2024-03-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_book_image_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
