# Generated by Django 5.0.2 on 2024-03-25 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 3, 25, 10, 4, 6, 813147, tzinfo=datetime.timezone.utc), upload_to='img/'),
            preserve_default=False,
        ),
    ]
