# Generated by Django 5.0.2 on 2024-03-26 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_book_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='time_period',
            field=models.CharField(default=datetime.datetime(2024, 3, 26, 7, 20, 16, 503667, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
    ]
