# Generated by Django 5.0.2 on 2024-03-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_book_time_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='time',
            new_name='time_create',
        ),
    ]
