# Generated by Django 5.0.2 on 2024-03-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_rename_time_book_time_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='time_create',
            new_name='time',
        ),
    ]
