# Generated by Django 5.0.2 on 2024-03-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_rename_time_create_book_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='time',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='time',
            new_name='time_create',
        ),
    ]
